
# SEO settings
title: "FX"
title2: "Algo"
title3: "Folio"
description: "Minimalist Open Source testing framework for algorithmic trading in forex."
keywords: "forex, algorithmic, trading, FOSS"
url: http://fxalgofolio.github.io # site url
# baseurl: "/fxalgofolio" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-79755062-2
repo: http://github.com/fxalgofolio/fxalgofolio.github.io
# disqus_shortname: "heiswayi"
# twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# social settings
og_locale: "en_US"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
